### ISSUE TITLE
Allow user to specify tree=FALSE when serial is specified. 

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/bpmodels#16]
Currently, the user gets an error when they specify `serial` with `tree = FALSE`. I think this might be harsh on them. Maybe, we can make it more flexible by allowing that specification to happen, except that we'll set `tree = TRUE` internally and tell the user what happened.

**Comment by sbfnk** [comment]
Yes, that seems fine. If we think that this is all a bit confusing, we could also consider splitting this into two functions, `chain_sim` and `tree_sim`.

**Comment by jamesmbaazam** [comment]
Thinking this issue might somehow address #4
