### ISSUE TITLE
Terminology: serial interval vs generation time

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/bpmodels#18]
At the moment the package references the serial interval in describing the time between cases. Technically this should be the generation time, as time between infections. In practice, this distinction probably doesn't matter here as we don't have model of latent infections that lead to symptoms, i.e. implicitly assume that symptom onset is the same as infection/infectiousness onset.

We should either switch the terminology to use generation times, or mention the assumption somewhere explicitly (my preference being for the second option).

**Comment by jamesmbaazam** [comment]
I think I prefer the second option too. I can add an explicit assumption to the documentation of chain_sim().
