### ISSUE TITLE
add a condition to `offspring` in `chain_ll` function that checks for the current supported distributions

### ISSUE THREAD

**Issue by Karim-Mane** [epiverse-trace/bpmodels#64]
--------
it would be good to check if the specified distribution is accounted for by your current release.

If not, it should bounce back with a message about the current supported distributions.

I have tried providing a normal distribution in chain_sim() but got an error
```r
chain_sim(n = 5, offspring = "norm", stat = "size")
```

---------

**Comment by jamesmbaazam** [comment]
Thanks, Karim. 

The supplied offspring function/distribution must produce integer values. 

I will try and spin a solution that checks this issue.

**Comment by sbfnk** [comment]
Isn't this already happening?

E.g., I get
```r
> library("bpmodels")
> chain_sim(n = 5, offspring = "norm", stat = "size")
Error in chain_sim(n = 5, offspring = "norm", stat = "size") : 
  Offspring distribution must return integers
```
which is the "correct" error.

> If not, it should bounce back with a message about the current supported distributions.

This is a nice idea but tricky because it supports any distribution (including custom supplied by the user) that returns integers.

**Comment by sbfnk** [comment]
Closing this for now but please re-open if I've misunderstood.
